[package]
name = "agent-arcade"
version = "0.1.0"
authors = ["Agent Arcade Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.0.0"
uint = { version = "0.9.3", default-features = false }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[reproducible_build]
# Reproducible build settings
protocol_version = 1
release = true
strip = true 