[package]
name = "agent-arcade"
version = "0.1.0"
authors = ["Agent Arcade Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "5.0.0", features = ["legacy", "abi", "schemars"] }
uint = { version = "0.9.3", default-features = false }
borsh = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[package.metadata.near.reproducible_build]
# Reproducible build settings
release = true
target = "wasm32-unknown-unknown"
strip = true
opt_level = "z"
features = ["legacy", "abi"]
debug = false
lto = true
debug_assertions = false
overflow_checks = true
rpath = false
codegen_units = 1
panic = "abort"
image = "stable" 