# Space Invaders Training Configuration - Quick Start

# Training parameters
total_timesteps: 100000    # ~15 minutes initial training
learning_rate: 0.001       # Faster initial learning
buffer_size: 10000        # Small buffer for quick learning
learning_starts: 1000     # Start learning very early
batch_size: 32           # Standard batch size
exploration_fraction: 0.3 # Faster exploration
target_update_interval: 500  # Frequent updates
frame_stack: 4           # Standard frame stacking

# Environment settings
env_id: "ALE/SpaceInvaders-v5"
frame_skip: 4            # Standard frame skip
noop_max: 30            # Standard no-op
num_envs: 4             # Parallel environments for faster training
fire_reset: true        # Required for Space Invaders

# Model architecture (optimized for speed)
policy: "CnnPolicy"      # Standard policy
features_extractor: "NatureCNN"  # Efficient CNN
features_dim: 256       # Reduced feature dimension

# Training optimizations
train_freq: 2           # Update frequently
gradient_steps: 1       # One step per update
exploration_initial_eps: 1.0
exploration_final_eps: 0.1
max_grad_norm: 10
device: "auto"          # Use GPU if available

# Note: For better performance after initial training, you can:
# 1. Increase total_timesteps to 250000
# 2. Decrease learning_rate to 0.00025
# 3. Increase buffer_size to 50000
# 4. Increase learning_starts to 10000
# 5. Decrease exploration_fraction to 0.2

# Evaluation settings
eval_episodes: 10       # Quick evaluation
eval_deterministic: true
render_eval: false

# Preprocessing
normalize_images: true    # Normalize pixel values
grayscale: true          # Convert to grayscale
resize_shape: [84, 84]   # Input image size

# Logging
tensorboard_log: true    # Enable TensorBoard logging
save_freq: 50000       # Save frequency in timesteps
log_interval: 100      # Logging interval in timesteps 