# Space Invaders Training Configuration

# Training parameters
total_timesteps: 2000000  # Total training steps (longer for complexity)
learning_rate: 0.0001     # Lower learning rate for stability
buffer_size: 500000       # Larger buffer for more experience
learning_starts: 100000   # More exploration before learning
batch_size: 128          # Smaller batches for better generalization
exploration_fraction: 0.1 # Less exploration
target_update_interval: 1000  # Target network update frequency
frame_stack: 4           # Number of frames to stack

# Environment settings
env_id: "ALE/SpaceInvaders-v5"
frame_skip: 4            # Number of frames to skip
noop_max: 30            # Max random no-ops at start
episodic_life: true     # End episode on life loss
fire_reset: true        # Fire on reset if applicable

# Model architecture
policy: "CnnPolicy"      # Policy network type
features_extractor: "NatureCNN"  # CNN architecture
features_dim: 512       # Feature dimension
double_q: true         # Use double Q-learning
dueling: true          # Use dueling network architecture

# Preprocessing
normalize_images: true   # Normalize pixel values
grayscale: true         # Convert to grayscale
resize_shape: [84, 84]  # Input image size
clip_rewards: true      # Clip rewards to [-1, 1]

# Evaluation settings
eval_episodes: 100      # Episodes for evaluation
eval_deterministic: true # Use deterministic actions
render_eval: false      # Render during evaluation

# Logging
tensorboard_log: true   # Enable TensorBoard logging
save_freq: 200000       # Save frequency in timesteps
log_interval: 1000      # Logging interval in timesteps

# Advanced settings
gradient_steps: 1       # Gradient steps per environment step
train_freq: 4          # Update frequency
learning_rate_schedule: "linear"  # Learning rate schedule 