algo: "DQN"
env: "ALE/SpaceInvaders-v5"

# Core Training Parameters
total_timesteps: 2000000  # 2M steps for efficient learning
learning_rate: 0.00025    # Standard DQN learning rate
buffer_size: 200000       # Reduced from 1M for memory efficiency
learning_starts: 50000    # Allow environment exploration before learning
batch_size: 64           # Balanced for stability and speed
train_freq: 4            # Update every 4 steps
gradient_steps: 1        # One gradient step per update
target_update_interval: 10000  # Standard DQN target update frequency
tau: 1.0                 # Hard update of target network
gamma: 0.99             # Standard discount factor

# Exploration Strategy
exploration_fraction: 0.1      # Faster exploration decay
exploration_initial_eps: 1.0   # Start fully random
exploration_final_eps: 0.05    # Maintain some exploration

# Network Architecture
policy_kwargs:
  net_arch: []  # Empty list for Nature CNN architecture
  features_extractor_class: "NatureCNN"
  features_extractor_kwargs:
    features_dim: 512
  normalize_images: true

# Environment Settings
n_envs: 8                # Parallel environments for faster training
frame_stack: 4           # Standard for Atari
optimize_memory_usage: true
max_grad_norm: 10       # Gradient clipping
terminal_on_life_loss: true
episode_life: true
clip_reward: false       # Disable reward clipping for better score differentiation
screen_size: 84
frame_skip: 4
noop_max: 30

# Training Monitoring
train_log_interval: 100   # Frequent logging
eval_freq: 25000         # Regular evaluation
n_eval_episodes: 5       # Quick evaluation
video_interval: 25000    # Regular video recording
video_length: 200        # Shorter videos for efficiency
checkpoint_freq: 50000   # Regular checkpoints

# Paths
save_path: "models/space_invaders_optimized"
tensorboard_log: "tensorboard/DQN_space_invaders_optimized"

# Performance Settings
device: "auto"
verbose: 1

# Preprocessing
grayscale: true
normalize_frames: true    # Enable frame normalization

# Save Settings
checkpoint_interval: 25000 